import torch; print(f'torch: {torch.__version__}')
import transformers; print(f'transformers: {transformers.__version__}')
import pypinyin; print(f'pypinyin: {pypinyin.__version__}')
import cn2an; print(f'cn2an: {cn2an.__version__}')
import jieba; print(f'jieba: {jieba.__version__}')
import g2p_en; print(f'g2p_en: ok')
import librosa; print(f'librosa: {librosa.__version__}')
import soundfile; print(f'soundfile: {soundfile.__version__}')
from melo.api import TTS; print('melo.api TTS: ok')
print('All key dependencies OK')
